version: '3.6'

services:
  bothub-webapp:
    image: ${BOTHUB_WEBAPP_DOCKER_IMAGE_NAME:-weni/weni-webapp}
    build:
      context: .
      dockerfile: Dockerfile
      args:
    ports:
      - 80:80
