version: '3.6'

services:
  connect-webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_ROOT_API=${VITE_ROOT_API:-http://api-connect.push.al}
        - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
        - KEYCLOAK_AUTHORIZATION_ENDPOINT=${KEYCLOAK_AUTHORIZATION_ENDPOINT}
        - KEYCLOAK_USERINFO_ENDPOINT=${KEYCLOAK_USERINFO_ENDPOINT}
        - KEYCLOAK_END_SESSION_ENDPOINT=${KEYCLOAK_END_SESSION_ENDPOINT}
        - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
        - KEYCLOAK_TOKEN_ENDPOINT=${KEYCLOAK_TOKEN_ENDPOINT}
        - KEYCLOAK_CHECK_SESSION_IFRAME=${KEYCLOAK_CHECK_SESSION_IFRAME}
        - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
        - KEYCLOAK_REALM=${KEYCLOAK_REALM}
        - VITE_HOTJAR_PROJECT_KEY=${VITE_HOTJAR_PROJECT_KEY}
        - VITE_BOT_URL=${VITE_BOT_URL}
        - VITE_SENTRY_DSN_ENDPOINT=${VITE_SENTRY_DSN_ENDPOINT}
        - VITE_HELPHERO=${VITE_HELPHERO}
        - VITE_URL_ACADEMY=${VITE_URL_ACADEMY}
        - VITE_BILLING_API_URL=${VITE_BILLING_API_URL}
        - MP9_AB_MAPPING_TOKEN=${MP9_AB_MAPPING_TOKEN}
    ports:
      - 8080:8080
