version: '3.6'

services:
  connect-webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_ROOT_API=${VUE_APP_ROOT_API:-http://api-connect.push.al}
        - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
        - KEYCLOAK_AUTHORIZATION_ENDPOINT=${KEYCLOAK_AUTHORIZATION_ENDPOINT}
        - KEYCLOAK_USERINFO_ENDPOINT=${KEYCLOAK_USERINFO_ENDPOINT}
        - KEYCLOAK_END_SESSION_ENDPOINT=${KEYCLOAK_END_SESSION_ENDPOINT}
        - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
        - KEYCLOAK_TOKEN_ENDPOINT=${KEYCLOAK_TOKEN_ENDPOINT}
        - KEYCLOAK_CHECK_SESSION_IFRAME=${KEYCLOAK_CHECK_SESSION_IFRAME}
        - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
        - KEYCLOAK_REALM=${KEYCLOAK_REALM}
        - VUE_APP_HOTJAR_PROJECT_KEY=${VUE_APP_HOTJAR_PROJECT_KEY}
        - VUE_APP_BOT_URL=${VUE_APP_BOT_URL}
        - VUE_APP_SENTRY_DSN_ENDPOINT=${VUE_APP_SENTRY_DSN_ENDPOINT}
        - VUE_APP_HELPHERO=${VUE_APP_HELPHERO}
        - VUE_APP_URL_ACADEMY=${VUE_APP_URL_ACADEMY}
        - MP9_AB_MAPPING_TOKEN=${MP9_AB_MAPPING_TOKEN}
    ports:
      - 8080:8080
