name: Run Unit Tests, Lint Files and Build Project 

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Tests Coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build application
        run:  yarn build
      - name: Run lint
        run: yarn lint
      - name: Run Unit Tests
        run: yarn test:unit
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
